liberary;-
collection of code, which contain module and classes

syntex - 
import from as

In [2]:
from matharea import area as a

In [3]:
a.rectangle_area(5,4)

20

In [4]:
a.circle_area(4)

50.24

# NUMPY LIBERARY 

In [5]:
import numpy as np

### 1D array

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(5,)

In [9]:
a[a-1]

array([1, 2, 3, 4, 5])

### 2d array - matrix

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b[[1,1],[1,2]] # because indexing starts from 0

array([5, 6])

ROW,COLOUM

In [12]:
#slicing
print(b[1,0:])
print(b[1,0:2])

[4 5 6]
[4 5]


In [13]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [40]:
print(b.shape, "ROW COLOUM")     
print(b.ndim)  #tell dimension of array

(3, 3) ROW COLOUM
2


### 3d array

In [15]:
c = np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
c

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [16]:
print(c.shape)
print("dimnession", c.ndim)

(2, 3, 2)
dimnession 3


In [19]:
c = np.array([[[1,1,1],[2,2,2],[3,3,3]], [[4,4,4],[5,5,5],[6,6,6]], [[7,7,7],[8,8,8],[9,9,9]]])
c

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]],

       [[7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]]])

In [39]:
print(c.shape, "PLANE ROW COLOUM")     
print(c.ndim)  #tell dimension of array

(3, 3, 3) PLANE ROW COLOUM
3


In [35]:
c[0:,0:,0] # PLANE ROW COLOUM

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

desire output coming in matrix form

In [41]:
c[:,:,:1]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [53]:
c[0:,1:2,0:]

array([[[2, 2, 2]],

       [[5, 5, 5]],

       [[8, 8, 8]]])

In [58]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
z[1][1] = 255
z

array([[  0.,   0.,   0.],
       [  0., 255.,   0.],
       [  0.,   0.,   0.]])